[package]
name = "reindexer-sys"
version = "0.1.0"
authors = ["Frank Zhou <529808348@qq.com>"]
edition = "2018"
# build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "*"
cc = "1.0"
